SELECT L_DATE, L_CODE, COUNT(*) AS CNT, SUM(L_TOTAL) AS TOTAL,
       SUM(SUM(L_TOTAL)) OVER(ORDER BY L_DATE, L_CODE) AS 누적대출금액
FROM loan
WHERE L_STORE = '1000'
GROUP BY L_DATE, L_CODE
ORDER BY L_DATE, L_CODE;
