SELECT L_CODE, L_STORE, L_DATE, COUNT(*) AS CNT, SUM(L_TOTAL) AS TOTAL,
       SUM(SUM(L_TOTAL)) OVER(PARTITION BY L_CODE, L_STORE ORDER BY L_DATE) AS 누적대출금액
FROM loan
GROUP BY L_CODE, L_STORE, L_DATE
ORDER BY L_CODE, L_STORE, L_DATE;
